name: CI for AI SDK Provider

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: listen.dev Scan
        uses: listendev/action@v0.11
        with:
          ci: only
          jwt: ${{ secrets.LSTN }} 
          argus_version: v0.0
          
      # Install dependencies
      - name: Install dependencies
        run: pnpm install
        
      # Clean build artifacts
      - name: Clean build artifacts
        run: pnpm run clean
        
      # Build project
      - name: Build project
        run: pnpm run build

  test:
      name: Test Code
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          
        - uses: pnpm/action-setup@v4
          with:
            version: 9
        - uses: listendev/action@v0.11
          with:
            ci: only
            jwt: ${{ secrets.LSTN }} 
            argus_version: v0.0
          
        - name: Install dependencies
          run: pnpm install
          
        # Run Node tests
        - name: Run Node Tests
          run: pnpm run test:node
          
        # Run Edge tests
        - name: Run Edge Tests
          run: pnpm run test:edge
